// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: esk8_s3

#include "../ui.h"

void ui_screenTrip_screen_init(void)
{
ui_screenTrip = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenTrip, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_screenTrip, &ui_img_bg_trip_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_buttonTrpBack = lv_imgbtn_create(ui_screenTrip);
lv_imgbtn_set_src(ui_buttonTrpBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_but_back_png, NULL);
lv_imgbtn_set_src(ui_buttonTrpBack, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_but_pres_back_png, NULL);
lv_obj_set_width( ui_buttonTrpBack, 60);
lv_obj_set_height( ui_buttonTrpBack, 60);
lv_obj_set_x( ui_buttonTrpBack, -120 );
lv_obj_set_y( ui_buttonTrpBack, 0 );
lv_obj_set_align( ui_buttonTrpBack, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_buttonTrpBack, ui_event_buttonTrpBack, LV_EVENT_ALL, NULL);

}
