// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: esk8_s3

#include "../ui.h"

void ui_screenBattery_screen_init(void)
{
ui_screenBattery = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenBattery, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_screenBattery, &ui_img_bg_bat_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_buttonBatBack = lv_imgbtn_create(ui_screenBattery);
lv_imgbtn_set_src(ui_buttonBatBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_but_back_png, NULL);
lv_imgbtn_set_src(ui_buttonBatBack, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_but_pres_back_png, NULL);
lv_obj_set_width( ui_buttonBatBack, 60);
lv_obj_set_height( ui_buttonBatBack, 60);
lv_obj_set_x( ui_buttonBatBack, -120 );
lv_obj_set_y( ui_buttonBatBack, 0 );
lv_obj_set_align( ui_buttonBatBack, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_buttonBatBack, ui_event_buttonBatBack, LV_EVENT_ALL, NULL);

}
