// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: esk8_s3

#include "../ui.h"

void ui_screenHome_screen_init(void)
{
ui_screenHome = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_screenHome,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_screenHome, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_img_src( ui_screenHome, &ui_img_bg_home_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_buttonBattery = lv_imgbtn_create(ui_screenHome);
lv_imgbtn_set_src(ui_buttonBattery, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_but_bat_png, NULL);
lv_imgbtn_set_src(ui_buttonBattery, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_but_pres_bat_png, NULL);
lv_obj_set_width( ui_buttonBattery, 60);
lv_obj_set_height( ui_buttonBattery, 60);
lv_obj_set_x( ui_buttonBattery, -110 );
lv_obj_set_y( ui_buttonBattery, 0 );
lv_obj_set_align( ui_buttonBattery, LV_ALIGN_CENTER );

ui_buttonNavigation = lv_imgbtn_create(ui_screenHome);
lv_imgbtn_set_src(ui_buttonNavigation, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_but_nav_png, NULL);
lv_imgbtn_set_src(ui_buttonNavigation, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_but_pres_nav_png, NULL);
lv_obj_set_width( ui_buttonNavigation, 60);
lv_obj_set_height( ui_buttonNavigation, 60);
lv_obj_set_x( ui_buttonNavigation, -30 );
lv_obj_set_y( ui_buttonNavigation, 0 );
lv_obj_set_align( ui_buttonNavigation, LV_ALIGN_CENTER );

ui_buttonTrip = lv_imgbtn_create(ui_screenHome);
lv_imgbtn_set_src(ui_buttonTrip, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_but_trp_png, NULL);
lv_imgbtn_set_src(ui_buttonTrip, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_but_pres_trip_png, NULL);
lv_obj_set_width( ui_buttonTrip, 60);
lv_obj_set_height( ui_buttonTrip, 60);
lv_obj_set_x( ui_buttonTrip, 30 );
lv_obj_set_y( ui_buttonTrip, 0 );
lv_obj_set_align( ui_buttonTrip, LV_ALIGN_CENTER );

ui_buttonSpeed = lv_imgbtn_create(ui_screenHome);
lv_imgbtn_set_src(ui_buttonSpeed, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_but_spd_png, NULL);
lv_imgbtn_set_src(ui_buttonSpeed, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_but_pres_spd_png, NULL);
lv_obj_set_width( ui_buttonSpeed, 60);
lv_obj_set_height( ui_buttonSpeed, 60);
lv_obj_set_x( ui_buttonSpeed, 110 );
lv_obj_set_y( ui_buttonSpeed, 0 );
lv_obj_set_align( ui_buttonSpeed, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_buttonBattery, ui_event_buttonBattery, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttonNavigation, ui_event_buttonNavigation, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttonTrip, ui_event_buttonTrip, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_buttonSpeed, ui_event_buttonSpeed, LV_EVENT_ALL, NULL);

}
