// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: esk8_s3

#include "../ui.h"

void ui_screenNavigation_screen_init(void)
{
ui_screenNavigation = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screenNavigation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_screenNavigation, &ui_img_bg_nav_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_buttonNavBack = lv_imgbtn_create(ui_screenNavigation);
lv_imgbtn_set_src(ui_buttonNavBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_but_back_png, NULL);
lv_imgbtn_set_src(ui_buttonNavBack, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_but_pres_back_png, NULL);
lv_obj_set_width( ui_buttonNavBack, 60);
lv_obj_set_height( ui_buttonNavBack, 60);
lv_obj_set_x( ui_buttonNavBack, -120 );
lv_obj_set_y( ui_buttonNavBack, 0 );
lv_obj_set_align( ui_buttonNavBack, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_buttonNavBack, ui_event_buttonNavBack, LV_EVENT_ALL, NULL);

}
