// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: esk8_s3

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screenHome
void ui_screenHome_screen_init(void);
lv_obj_t *ui_screenHome;
void ui_event_buttonBattery( lv_event_t * e);
lv_obj_t *ui_buttonBattery;
void ui_event_buttonNavigation( lv_event_t * e);
lv_obj_t *ui_buttonNavigation;
void ui_event_buttonTrip( lv_event_t * e);
lv_obj_t *ui_buttonTrip;
void ui_event_buttonSpeed( lv_event_t * e);
lv_obj_t *ui_buttonSpeed;


// SCREEN: ui_screenBattery
void ui_screenBattery_screen_init(void);
lv_obj_t *ui_screenBattery;
void ui_event_buttonBatBack( lv_event_t * e);
lv_obj_t *ui_buttonBatBack;


// SCREEN: ui_screenNavigation
void ui_screenNavigation_screen_init(void);
lv_obj_t *ui_screenNavigation;
void ui_event_buttonNavBack( lv_event_t * e);
lv_obj_t *ui_buttonNavBack;


// SCREEN: ui_screenTrip
void ui_screenTrip_screen_init(void);
lv_obj_t *ui_screenTrip;
void ui_event_buttonTrpBack( lv_event_t * e);
lv_obj_t *ui_buttonTrpBack;


// SCREEN: ui_screenSpeed
void ui_screenSpeed_screen_init(void);
lv_obj_t *ui_screenSpeed;
void ui_event_buttonSpdBack( lv_event_t * e);
lv_obj_t *ui_buttonSpdBack;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_buttonBattery( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenBattery, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_screenBattery_screen_init);
}
}
void ui_event_buttonNavigation( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenNavigation, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_screenNavigation_screen_init);
}
}
void ui_event_buttonTrip( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenTrip, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_screenTrip_screen_init);
}
}
void ui_event_buttonSpeed( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenSpeed, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_screenSpeed_screen_init);
}
}
void ui_event_buttonBatBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenHome, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_screenHome_screen_init);
}
}
void ui_event_buttonNavBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenHome, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_screenHome_screen_init);
}
}
void ui_event_buttonTrpBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenHome, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_screenHome_screen_init);
}
}
void ui_event_buttonSpdBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_screenHome, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_screenHome_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_screenHome_screen_init();
ui_screenBattery_screen_init();
ui_screenNavigation_screen_init();
ui_screenTrip_screen_init();
ui_screenSpeed_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_screenHome);
}
